max_jobs: 1

environment:
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: "true"

image: Visual Studio 2019

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

install:
  - cmd: dotnet tool restore

build_script:
  - cmd: dotnet cake --target=Full --SkipVerification=true

test: off

artifacts:
  - path: outputs\*.nupkg
    name: packages
  - path: outputs\*.snupkg
    name: symbols
  - path: outputs\tests\report
    name: report
    type: zip

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: Environment
    name: GitHub Packages - Kralizek
    on:
      branch: master
      appveyor_repo_tag: true